[Http]
Address = "0.0.0.0"
Port = 8004

[Logger]
Output = "stdout,file:///var/log/ip2location/app.%Y%m%d.log"
LogLevel = "info"

[General]
date-format = "2006-01-02 15:04:05.99999"
db-path = "db/"
download-cron = "0 0/3 * * * *"
file-city-url = "https://git.io/GeoLite2-City.mmdb"